### ISSUE TITLE
В чем ошибка?

### ISSUE THREAD

**Issue by laraketai** [aizhar777/laravel_mobizon#1]
Aizhar777 \ Mobizon \ Exceptions \ CouldNotSendNotification
Notification was not sent. Phone number is missing.

**Comment by aizhar777** [comment]
Phone number is missing. Номер телефона не найден.
Нужно в модель добавить метод:
`public function routeNotificationForMobizone()
{
    return $this->phone; // Номер телефона в международном формате
}`

**Comment by laraketai** [comment]
то же самое Notification was not sent. Phone number is missing. Вот моя модель:
`<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use TCG\Voyager\Traits\Translatable;
use Illuminate\Database\Eloquent\Model;


class ContactRequest extends Model
{

    use Notifiable;

    use Translatable;

    protected $table = "contactRequests";

    protected $translatable = ['name', 'mobile_no', 'message',];

    protected $fillable = [
        'name', 'mobile_no', 'message',
    ];

    public function routeNotificationForSlack() {
        return env('SLACK_WEBHOOK_URL');
    }

    public function routeNotificationForMobizone()
    {
        return $this->mobile_no;
    }
}
`

**Comment by aizhar777** [comment]
Опечатка в файле readme, позже исправлю, назови метод `routeNotificationForMobizon`

**Comment by laraketai** [comment]
Нет видимо ошибка в другом

**Comment by laraketai** [comment]
Репозитория нет, но могу отправить Model, Notification, Route и Controller на почту
